"""
Violation Record Schema
=======================
Strongly-typed Pydantic model representing a confirmed/final violation record generated by the decision engine.
"""
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field


class ViolationRecord(BaseModel):
    """
    Standardized payload for a single violation decision.
    """
    violation_id: str = Field(..., description="Unique UUID or string identifying this violation instance")
    tracking_id: int = Field(..., description="Track ID of the associated vehicle")
    verified_plate: Optional[str] = Field(default=None, description="Verified license plate number text if available")
    vehicle_class: int = Field(..., description="Vehicle class ID (e.g. 2=car, 3=motorcycle)")
    violation_type: str = Field(..., description="Type of violation (e.g. 'No Helmet', 'Wrong Side')")
    severity: str = Field(..., description="Severity of violation: Low, Medium, High, Critical")
    confidence: float = Field(..., description="Decision confidence score (0.0 to 1.0)")
    timestamp: float = Field(..., description="Timestamp of the violation decision")
    frame_id: int = Field(..., description="Frame index of the decision")
    rule_id: str = Field(..., description="Unique ID of the triggered rule")
    decision_status: str = Field(..., description="Decision state ('Confirmed', 'Rejected', 'Pending', 'Unknown')")
    evidence_required: bool = Field(default=True, description="Flag indicating if evidence capture is required")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Rule-specific details and context logs")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()
