from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from backend.app.database import get_db
from backend.app.models import Report, User, Violation, ActivityLog
from backend.app.auth.jwt import get_current_user
from pydantic import BaseModel
from typing import List, Optional
import datetime
import os
import csv

def generate_pdf_report(file_path: str, violations: List[Violation], title: str, report_type: str, start_date: datetime.datetime, end_date: datetime.datetime, generated_by_name: str):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors

    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    story = []
    styles = getSampleStyleSheet()

    # Define custom styles
    title_style = ParagraphStyle(
        name='TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1e3a8a'),
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        name='SubTitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        spaceAfter=20
    )
    cell_style = ParagraphStyle(
        name='CellStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1e293b')
    )
    header_style = ParagraphStyle(
        name='HeaderStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.white
    )

    # 1. Header Title
    story.append(Paragraph(title, title_style))
    
    # 2. Metadata Subtitle
    meta_text = (
        f"<b>Report Type:</b> {report_type.upper()} | "
        f"<b>Date Range:</b> {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}<br/>"
        f"<b>Generated By:</b> {generated_by_name} | "
        f"<b>Total Detections Logged:</b> {len(violations)} | "
        f"<b>Printed At:</b> {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"
    )
    story.append(Paragraph(meta_text, subtitle_style))
    story.append(Spacer(1, 10))

    # 3. Violations Table
    # Headers
    headers = [
        Paragraph("<b>ID</b>", header_style),
        Paragraph("<b>License Plate</b>", header_style),
        Paragraph("<b>Violation Type</b>", header_style),
        Paragraph("<b>Timestamp</b>", header_style),
        Paragraph("<b>Location</b>", header_style),
        Paragraph("<b>Fine (INR)</b>", header_style),
        Paragraph("<b>Status</b>", header_style),
        Paragraph("<b>Conf</b>", header_style)
    ]
    table_data = [headers]

    for v in violations:
        plate = v.vehicle.license_plate if v.vehicle else "N/A"
        row = [
            Paragraph(str(v.id), cell_style),
            Paragraph(plate, cell_style),
            Paragraph(v.type.replace('_', ' ').title(), cell_style),
            Paragraph(v.timestamp.strftime('%Y-%m-%d %H:%M:%S'), cell_style),
            Paragraph(v.location, cell_style),
            Paragraph(f"Rs. {v.fine_amount}", cell_style),
            Paragraph(v.status.upper(), cell_style),
            Paragraph(f"{int(v.confidence_score * 100)}%", cell_style)
        ]
        table_data.append(row)

    col_widths = [25, 65, 95, 95, 110, 50, 60, 40]
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    ts = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a8a')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#1e3a8a')),
    ])
    
    for r_idx in range(1, len(table_data)):
        bg_col = colors.HexColor('#f8fafc') if r_idx % 2 == 1 else colors.white
        ts.add('BACKGROUND', (0, r_idx), (-1, r_idx), bg_col)
        
    t.setStyle(ts)
    story.append(t)

    doc.build(story)

router = APIRouter(prefix="/reports", tags=["Reports"])

class ReportCreate(BaseModel):
    title: str
    report_type: str  # violations, revenue, analytics
    start_date: datetime.datetime
    end_date: datetime.datetime
    file_format: Optional[str] = "csv" # csv, xlsx, pdf

class ReportOut(BaseModel):
    id: int
    title: str
    generated_by: int
    report_type: str
    start_date: datetime.datetime
    end_date: datetime.datetime
    file_path: str
    created_at: datetime.datetime

    class Config:
        from_attributes = True

@router.get("", response_model=List[ReportOut])
def get_reports(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    return db.query(Report).order_by(Report.created_at.desc()).all()

@router.get("/{report_id}", response_model=ReportOut)
def get_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    rep = db.query(Report).filter(Report.id == report_id).first()
    if not rep:
        raise HTTPException(status_code=404, detail="Report log not found")
    return rep

@router.post("", response_model=ReportOut)
def generate_report(
    payload: ReportCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    import pandas as pd
    
    # Ensure directory exists
    report_dir = os.path.join("data", "reports")
    os.makedirs(report_dir, exist_ok=True)

    # Fetch violations within date range
    violations = db.query(Violation).filter(
        Violation.timestamp >= payload.start_date,
        Violation.timestamp <= payload.end_date
    ).all()

    # Generate filename
    timestamp_str = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
    
    if payload.file_format == "xlsx":
        filename = f"report_{payload.report_type}_{timestamp_str}.xlsx"
    elif payload.file_format == "pdf":
        filename = f"report_{payload.report_type}_{timestamp_str}.pdf"
    else:
        filename = f"report_{payload.report_type}_{timestamp_str}.csv"
        
    file_path = os.path.join(report_dir, filename)

    try:
        # Construct DataFrame
        data = []
        for v in violations:
            data.append({
                "Violation ID": v.id,
                "Vehicle ID": v.vehicle_id,
                "Camera ID": v.camera_id,
                "Violation Type": v.type,
                "Timestamp": v.timestamp.isoformat(),
                "Location": v.location,
                "Fine Amount": v.fine_amount,
                "Status": v.status,
                "Confidence Score": v.confidence_score
            })
            
        df = pd.DataFrame(data)
        
        if payload.file_format == "xlsx":
            df.to_excel(file_path, index=False)
        elif payload.file_format == "pdf":
            generate_pdf_report(
                file_path=file_path,
                violations=violations,
                title=payload.title,
                report_type=payload.report_type,
                start_date=payload.start_date,
                end_date=payload.end_date,
                generated_by_name=current_user.full_name
            )
        else:
            df.to_csv(file_path, index=False, encoding="utf-8")
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate report file: {e}")

    static_url = f"/data/reports/{filename}"

    rep = Report(
        title=payload.title,
        generated_by=current_user.id,
        report_type=payload.report_type,
        start_date=payload.start_date,
        end_date=payload.end_date,
        file_path=static_url
    )
    db.add(rep)
    db.commit()
    db.refresh(rep)

    # Log action
    log = ActivityLog(
        user_id=current_user.id,
        action=f"Generated '{payload.report_type}' report: '{payload.title}'"
    )
    db.add(log)
    db.commit()

    return rep

@router.delete("/{report_id}")
def delete_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    rep = db.query(Report).filter(Report.id == report_id).first()
    if not rep:
        raise HTTPException(status_code=404, detail="Report not found")

    # Optional: Delete file
    # We clean up file path if it exists locally
    local_path = rep.file_path.lstrip("/")
    if os.path.exists(local_path):
        try:
            os.remove(local_path)
        except OSError:
            pass

    title = rep.title
    db.delete(rep)
    db.commit()

    # Log action
    log = ActivityLog(
        user_id=current_user.id,
        action=f"Deleted report log: '{title}'"
    )
    db.add(log)
    db.commit()

    return {"success": True, "message": f"Deleted report log for '{title}'."}
