"""
Unit Tests for Report Repository, Service, and API Endpoints
============================================================
Asserts:
  1. PDF document formatting (ASCII cover page, KPIs, footers).
  2. CSV, Excel, and JSON report file compilation.
  3. Report database state lifecycle (generating -> completed/failed).
  4. Template metadata listing and query parameters.
  5. ZIP file export packaging.
  6. Endpoint routing parameters and dependency overrides.
"""
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session
from fastapi import Depends
from fastapi.testclient import TestClient
import datetime
import os
import shutil

from backend.app.database import Base
from backend.main import app
from backend.app.models import Violation, Vehicle, Camera, User, Report
from backend.app.models.email_log_model import EmailLogModel
from backend.app.services.report_service import report_service
from backend.app.schemas.report_schema import ReportCreate, ReportFilterSchema

# Use a clean file-based SQLite database for testing report operations
test_db_filename = "test_reports.db"
test_engine = create_engine(f"sqlite:///{test_db_filename}", connect_args={"check_same_thread": False})
TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=test_engine)

mock_user = User(id=9, username="test_reporter", email="rep@gmail.com", full_name="Test Reporter", password_hash="hash", status="active")


@pytest.fixture(autouse=True)
def setup_test_database():
    # Remove old test DB if it exists
    if os.path.exists(test_db_filename):
        try:
            os.remove(test_db_filename)
        except Exception:
            pass

    # Ensure reports directory exists
    os.makedirs(os.path.join("data", "reports"), exist_ok=True)
            
    # Recreate tables for each test run
    Base.metadata.create_all(bind=test_engine)
    
    # Seed mock data
    db = TestSessionLocal()
    db.add(mock_user)
    
    # Create Cameras
    c1 = Camera(id="CAM_01", name="Main Gate", location="GPS: 10,20", status="online", lat=10.0, lng=20.0)
    db.add(c1)
    
    # Create Vehicles
    v1 = Vehicle(id=1, license_plate="MH12AB1234", type="car", brand="Toyota")
    db.add(v1)
    
    # Create Violations
    vi1 = Violation(
        id=1,
        vehicle_id=1,
        camera_id="CAM_01",
        type="No Seat Belt",
        timestamp=datetime.datetime(2026, 7, 9, 10, 0, 0),
        location="GPS: 10,20",
        fine_amount=500.0,
        status="pending",
        confidence_score=0.88
    )
    db.add(vi1)
    
    db.commit()
    db.close()
    
    yield
    Base.metadata.drop_all(bind=test_engine)
    
    # Clean up test database file
    if os.path.exists(test_db_filename):
        try:
            os.remove(test_db_filename)
        except Exception:
            pass
            
    # Clean up generated test reports
    reports_dir = os.path.join("data", "reports")
    if os.path.exists(reports_dir):
        for f in os.listdir(reports_dir):
            if f.startswith("report_"):
                try:
                    os.remove(os.path.join(reports_dir, f))
                except Exception:
                    pass


def test_pdf_report_generation():
    db = TestSessionLocal()
    
    payload = ReportCreate(
        title="Official Traffic Audit",
        report_type="daily_summary",
        start_date=datetime.datetime(2026, 7, 1),
        end_date=datetime.datetime(2026, 7, 10),
        format="pdf",
        filters=ReportFilterSchema()
    )
    
    report = report_service.generate_report(db, user_id=9, payload=payload)
    
    assert report.status == "completed"
    assert report.format == "pdf"
    assert "Official Traffic Audit" in report.title
    
    filename = os.path.basename(report.file_path)
    physical_path = os.path.join("data", "reports", filename)
    assert os.path.exists(physical_path)
    
    with open(physical_path, "r", encoding="utf-8") as f:
        content = f.read()
        assert "OFFICIAL REPORT" in content
        assert "EXECUTIVE KPI SUMMARY" in content
        assert "Generated by Traffic Violation AI" in content

    db.close()


def test_csv_report_generation():
    db = TestSessionLocal()
    
    payload = ReportCreate(
        title="Export Sheet",
        report_type="weekly_trends",
        start_date=datetime.datetime(2026, 7, 1),
        end_date=datetime.datetime(2026, 7, 10),
        format="csv",
        filters=ReportFilterSchema()
    )
    
    report = report_service.generate_report(db, user_id=9, payload=payload)
    assert report.status == "completed"
    
    filename = os.path.basename(report.file_path)
    physical_path = os.path.join("data", "reports", filename)
    assert os.path.exists(physical_path)
    
    with open(physical_path, "r", encoding="utf-8") as f:
        content = f.read()
        assert "License Plate" in content

    db.close()


def test_api_report_endpoints():
    from backend.app.database import get_db
    from backend.app.auth.jwt import get_current_user
    
    # Setup dependency overrides for FastAPI TestClient
    def override_get_db():
        db = TestSessionLocal()
        try:
            yield db
        finally:
            db.close()
            
    def override_get_current_user(db: Session = Depends(override_get_db)):
        user = db.query(User).filter(User.username == "test_reporter").first()
        if not user:
            user = User(
                id=9,
                username="test_reporter",
                email="rep@gmail.com",
                full_name="Test Reporter",
                password_hash="hash",
                status="active"
            )
            db.add(user)
            db.commit()
            db.refresh(user)
        return user
        
    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = override_get_current_user
    
    try:
        client = TestClient(app)

        # 1. Fetch available templates
        res = client.get("/api/v1/reports/templates")
        assert res.status_code == 200
        assert len(res.json()) > 0
        assert res.json()[0]["id"] == "daily_summary"

        # 2. Trigger report generation
        payload = {
            "title": "API Daily Summary",
            "report_type": "daily_summary",
            "start_date": "2026-07-01T00:00:00",
            "end_date": "2026-07-10T23:59:59",
            "format": "pdf",
            "filters": {}
        }
        res = client.post("/api/v1/reports/generate", json=payload)
        assert res.status_code == 201
        report_data = res.json()
        assert report_data["status"] == "completed"
        report_id = report_data["id"]

        # 3. Download generated file
        res = client.get(f"/api/v1/reports/download/{report_id}")
        assert res.status_code == 200
        assert "application/pdf" in res.headers["content-type"]

        # 4. Fetch history list
        res = client.get("/api/v1/reports")
        assert res.status_code == 200
        assert len(res.json()) >= 1
        assert res.json()[0]["title"] == "API Daily Summary"

        # 5. Fetch history audit
        res = client.get("/api/v1/reports/history")
        assert res.status_code == 200
        assert len(res.json()) >= 1

        # 6. Export ZIP package
        res = client.get("/api/v1/reports/export")
        assert res.status_code == 200
        assert "application/x-zip-compressed" in res.headers["content-type"]

        # 7. Get engine health status
        res = client.get("/api/v1/reports/health")
        assert res.status_code == 200
        assert res.json()["engine_status"] == "healthy"

        # 8. Delete report record
        res = client.delete(f"/api/v1/reports/delete/{report_id}")
        assert res.status_code == 200
        assert res.json()["success"] is True

    finally:
        app.dependency_overrides.clear()
